# @format

name-template: "v$RESOLVED_VERSION ✨"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
  - title: "🧰 Maintenance"
    label: "housekeeping"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
autolabeler:
  - label: "bug"
    branch:
      - '/hotfix\/.+/'
      - '/quickfix\/.+/'
  - label: "feature"
    branch:
      - '/feature\/.+/'
  - label: "housekeeping"
    files:
      - "*.md"
      - "*.txt"
    branch:
      - '/docs{0,1}\/.+/'
template: |
  ## What's Changed 🎉

  $CHANGES
